#logging:
#  level:
#    root: DEBUG
#    jasypt: DEBUG
spring:
  sql:
    init:
      encoding: utf-8

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true

  datasource:
    url: ENC(6Y9h/qRijEfMAVsFTk1wTd+Q7/mC9gehWhlLq6EkUSgJmP5xT0E3uu/qUOGYcbhlznlOqf0gIENlRWh/B1DxKK+YUTAK2Ip9gyG+no9ywW/eqNTbyphf9AKbE4OaN+AG04CD+gDt3NSDZetRVQBbJQ+lQaEmYXOqXPr3BWCmeDMDKmNh4tHeqfvq+Ec05wEkLXz3NGQfz3c=)
    username: ENC(Y7isrGL6/Iv3vTOaqDzg75PUG0L123To)
    password: ENC(M5qMqRli8rtm8adpY1EJF1d26qgXkuUSqpe5vCsl4yo=)
    sql-script-encoding: utf-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(UQ3PMQLthZmySO2ibFEyOyRC3ilP3iccfweRbN1q3RN9AnNYm3VnGeYlLuQXpKuLbvCMJtq+dSbMmvZR4va/m6IVC4SKsjXyoyo9Adr/qthKKiw9FW+mhQ4bd4ZFca8+)
            client-secret: ENC(3wrcwmN4d296K+Zyr6LcGTg5Zl+4XuvBrzB6OJYdRqC+SmykR4JkpwD2tCqNHUwTLRKuoDtsRRI=)
            scope:
              - email
              - profile

          kakao:
            client_id: ENC(wUy7wK2KHrMjGMyAH30O+7I2ecLiTnHZvXl7U7aRRAzMBCskqpFiK+zE+Ixp/mUIYIQVNd5CLbI=)
            redirect_uri: http://localhost:8080/oauth2/kakao
            response_type: code
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: openid, profile_nickname, profile_image, account_email

          naver:
            client_id : ENC(3IHoYU4aMmaFoYT1sbRHtNPKkUbS6R7dBnPLEQht0Gj+HVgyYJ/fKw==)
            client-secret: ENC(40Trp1nyJ8Sd7wqLRv0XK+ho+PifHnrpl0sNBZZISZM=)
            response_type: code
            redirect_uri: http://localhost:8080/oauth2/naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



jwt:
  issuer: cr0c0
  secret_key: ENC(/BCY1rKWxF49AOfCLtGSlj0ygUf9kk+70Rc/NNnp0CNrDvTquUkAOZl1IFS5fYef)

file:
  upload:
    path: resources/static/image/

apiKey:
  aladin: ENC(qlX7ujIj5Q43k1Z6WOB9Rfnm5swpp4BVOAJKsaEkt+iQzzg+X0k85g==)
  imgBB: ENC(3COeQD3IOuvV9sLL+5enqxsw4xa6qSb1w40h9o292kD8V3wEayy2c70idONz7LejasdFT3AKJuY=)

aws:
  access_key: ENC(9wD9vfQJIT1AXWNKBgsvjRqiiOUUudzn4SlbwpAx+LXy+5Hc8TLX3Q==)
  secret_key: ENC(TzFpH8P6hW0PV/Xz1GTAUAT/2XmTI/wuhehfgpUdpCbVC8o1RkuLlRBcNbEhRVLNPGFMyg5nHuUWzLrKtwO2fQ==)


