#logging:
  #level:
    #root: DEBUG
    #jasypt: DEBUG

spring:
  sql:
    init:
      encoding: utf-8

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true

  datasource:
    url: ENC(6Y9h/qRijEfMAVsFTk1wTd+Q7/mC9gehWhlLq6EkUSgJmP5xT0E3uu/qUOGYcbhlznlOqf0gIENlRWh/B1DxKK+YUTAK2Ip9gyG+no9ywW/eqNTbyphf9AKbE4OaN+AG04CD+gDt3NSDZetRVQBbJQ+lQaEmYXOqXPr3BWCmeDMDKmNh4tHeqfvq+Ec05wEkLXz3NGQfz3c=)
    username: ENC(Y7isrGL6/Iv3vTOaqDzg75PUG0L123To)
    password: ENC(M5qMqRli8rtm8adpY1EJF1d26qgXkuUSqpe5vCsl4yo=)
    sql-script-encoding: utf-8

jwt:
  issuer: cr0c0
  secret_key: ENC(/BCY1rKWxF49AOfCLtGSlj0ygUf9kk+70Rc/NNnp0CNrDvTquUkAOZl1IFS5fYef)



